name:                pietc
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- file-embed
- JuicyPixels
- lens
- list-t
- llvm-hs
- llvm-hs-pure
- mtl
- primitive
- transformers
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  pietc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - pietc

tests:
  pietc-test:
    main:                Spec.hs
    source-dirs:         test
    c-sources:
    - test/llvmtestutils.c
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - pietc
    - hspec
    - directory
    - interpolatedstring-perl6
    - llvm-hs-pretty
    - text
