name:                pietc
version:             1.0.2

ghc-options:
- -Wall
- -Werror
- -Widentities
- -Wmissing-export-lists
- -Wmissing-exported-signatures
- -Wpartial-fields
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- file-embed
- JuicyPixels
- lens
- list-t
- llvm-hs
- llvm-hs-pure
- mtl
- primitive
- process
- text
- transformers
- vector

library:
  source-dirs: src

executables:
  pietc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pietc
    - optparse-applicative

tests:
  pietc-test:
    main:                Spec.hs
    source-dirs:         test
    c-sources:
    - test/llvmtestutils.c
    dependencies:
    - pietc
    - hspec
    - interpolatedstring-perl6
    - llvm-hs-pretty
