name:                pietc
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- file-embed
- JuicyPixels
- lens
- list-t
- llvm-hs
- llvm-hs-pure
- mtl
- primitive
- process
- text
- transformers
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -Widentities
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  pietc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Widentities
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - pietc
    - optparse-applicative

tests:
  pietc-test:
    main:                Spec.hs
    source-dirs:         test
    c-sources:
    - test/llvmtestutils.c
    ghc-options:
    - -Wall
    - -Werror
    - -Widentities
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - pietc
    - hspec
    - interpolatedstring-perl6
    - llvm-hs-pretty
