name:                pietc
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- list-t
- mtl
- primitive
- transformers
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  pietc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - pietc

tests:
  pietc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - pietc
    - hspec
    - interpolatedstring-perl6
